" Use Vim settings, rather then Vi settings. This setting must be as early as
" possible, as it has side effects.
set nocompatible

syntax on

filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Bundles
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

filetype on

" Config
if filereadable(expand("~/.vimrc.config"))
  source ~/.vimrc.config
endif

" Keymap
if filereadable(expand("~/.vimrc.keymap"))
  source ~/.vimrc.keymap
endif

filetype plugin indent on

" Powerline
" python from powerline.vim import setup as powerline_setup
" python powerline_setup()
" python del powerline_setup
